//============================================================================
// comb_ckt_generator.v
//
// This code is generated by Terasic System Builder
// and modified by M. Hildebrand and B. Baas
//
// 2018/02/05 First version
// 2018/04/24 Routed all board-level switches and LEDs to and from this module
//============================================================================

module comb_ckt_generator (
   // VGA-related signals
   col,
   row,
   red,
   green,
   blue,
   // input push buttons and switches
   KEY,
   SW,
   // output LEDs and 7-segment displays
   LEDR,
   HEX0,
   HEX1,
   HEX2,
   HEX3,
   HEX4,
   HEX5
   );

input  [9:0]  col;
input  [8:0]  row;
output [3:0]  red;    // 4-bit color output
output [3:0]  green;  // 4-bit color output
output [3:0]  blue;   // 4-bit color output

// input push buttons and switches
input  [1:0]  KEY;    // two board-level push buttons KEY1 - KEY0
input  [9:0]  SW;     // ten board-level switches SW9 - SW0

// output LEDs and 7-segment displays
output [9:0]  LEDR;   // ten board-level LEDs LEDR9 - LEDR0
output [7:0]  HEX0;   // board-level 7-segment display
output [7:0]  HEX1;   // board-level 7-segment display
output [7:0]  HEX2;   // board-level 7-segment display
output [7:0]  HEX3;   // board-level 7-segment display
output [7:0]  HEX4;   // board-level 7-segment display
output [7:0]  HEX5;   // board-level 7-segment display


//============================================================================
//  reg/wire declarations
//============================================================================
// More complex implementations will likely declare RGB outputs as regs
// rather than wires
reg [3:0]    red, green, blue;    


//============================================================================
// Board-LED related circuits
//============================================================================

// Temporary simple logic
// The 10 LEDs will light depending on the position of the adjacent 10 switches
assign LEDR = SW;      // ten LEDs assigned to ten switches

// Temporary simple logic
// This block sets the 7-segment HEX displays
// HEX4 - HEX0 are set to all dark
// HEX5 lights segments based on SW9 - SW2
assign HEX0 = 8'b1111_1111;
assign HEX1 = 8'b1111_1111;
assign HEX2 = 8'b1111_1111;
assign HEX3 = 8'b1111_1111;
assign HEX4 = 8'b1111_1111;
assign HEX5 = ~{SW[9], SW[8], SW[7], SW[6], SW[5], SW[4], SW[3], SW[2]};


//==============================================================
// VGA display related circuits
//==============================================================

// Temporary simple logic
// Full intensity is SW[0] is '1'. Blank otherwise
always@(SW)begin
       red = 4'b1111;
	    green = 4'b1111;
	    blue = 4'b1111; 
  if (SW[0]==1 && SW[1]==0)begin 
	//2'b01:begin
	  if(col == 10'd0320 && row > 9'd120 && row < 9'd360 )
	   begin
	    red = 4'b1001;
	    green = 4'b1001;
	    blue = 4'b1001;
		 $display("12");
		end
	end
  else if (SW[1]==1 && SW[0]==0)begin
	//2'b10:begin
	  if(col > 10'd0160 && col < 10'd480 && row == 9'd240 )
	   begin
	    red = 4'b1010;
	    green = 4'b1010;
	    blue = 4'b1010;
		 $display("13");
		end
	end 
  else if (SW[0]==1 && SW[1]==1)begin
      if(col > 10'd0160 && col < 10'd480 && row > 9'd120 && row < 9'd 360)
	   begin
	    red = 4'b0101;
	    green = 4'b0101;
	    blue = 4'b0101;
		 $display("14");
		end
	end
  /////////////////////////////////////
  else if (SW[2]==1 && SW[3]==0)begin
	      red = 4'b1000;
	      green = 4'b1101;
	      blue = 4'b1111;
	      $display("22");
  end
  else if (SW[3]==1 && SW[2]==0)begin
	//2'b10:begin
	     red = 4'b0010;
	     green = 4'b0100;
	     blue = 4'b0111;
	     $display("23");
  end
  else if (SW[3]==1 && SW[2]==1)begin	
	//2'b11:begin
	     red = 4'b1110;
	     green = 4'b1011;
	     blue = 4'b0010;
	     $display("24");
  end
///////////////////////////////////////////
	//2'b11:begin
	  
  else if (SW[8]==0 && SW[9]==0)begin 
	//2'b00:begin
	  if(col<=10'd0060 && col>=10'd0000 && row<=9'd080 && row >=9'd000)
	   begin
	    red = 4'b0000;
		 green = 4'b0000;
		 blue = 4'b0000;
		 $display("71");
		 if (SW[4]==0)begin
	//1'b1:begin
	      if(col == 10'd0000 || col == 10'd0060 || row == 9'd000 || row == 9'd080)
	      begin
	      red = 4'b0000;
		   green = 4'b0000;
		   blue = 4'b0000;
		   $display("32");
		   end
	    end
       if (SW[4]==1)begin
	//1'b1:begin
	    if(col != 10'd0000 && col != 10'd0060 && row != 9'd000 && row != 9'd080)
	      begin
	      red = 4'b1111;
		   green = 4'b1111;
		   blue = 4'b1111;
		   $display("32");
		   end
	    end
       else if (SW[5]==1)begin
	//1'b1:begin
	      blue = 4'b1111;
	      $display("42");
	    end
       else if (SW[6]==1)begin
	//1'b1:begin
	     green = 4'b1111;
	     $display("52");
	    end
       else if (SW[7]==1)begin
	//1'b1:begin
	     red = 4'b1111;
	     $display("62");
	    end
	  end
  end
  else if (SW[8]==1 && SW[9]==0)begin
	//2'b01:begin
	  if(col<=10'd0640 && col>=10'd0580 && row<=9'd080 && row >=9'd000)
	   begin
	    red = 4'b0000;
		 green = 4'b0000;
		 blue = 4'b0000;
		 $display("72");
		 if (SW[4]==0)begin
	//1'b1:begin
	    if(col == 10'd0640 || col == 10'd0580 || row == 9'd080 || row == 9'd000)
	      begin
	      red = 4'b0000;
		   green = 4'b0000;
		   blue = 4'b0000;
		   $display("32");
		   end
	    end
       if (SW[4]==1)begin
	//1'b1:begin
	    if(col != 10'd0640 && col != 10'd0580 && row != 9'd080 && row != 9'd000)
	      begin
	      red = 4'b1111;
		   green = 4'b1111;
		   blue = 4'b1111;
		   $display("32");
		   end
	    end
       else if (SW[5]==1)begin
	//1'b1:begin
	      blue = 4'b1111;
	      $display("42");
	    end
       else if (SW[6]==1)begin
	//1'b1:begin
	     green = 4'b1111;
	     $display("52");
	    end
       else if (SW[7]==1)begin
	//1'b1:begin
	     red = 4'b1111;
	     $display("62");
	    end
		end
	end
  else if (SW[9]==1 && SW[8]==0)begin
	//2'b10:begin
	  if(col<=10'd0060 && col>=10'd0000 && row<=9'd480 && row >=9'd400)
	   begin
	    red = 4'b0000;
		 green = 4'b0000;
		 blue = 4'b0000;
		 $display("73");
		 if (SW[4]==0)begin
	//1'b1:begin
	    if(col == 10'd0000 || col == 10'd0060 || row == 9'd480 || row == 9'd400)
	      begin
	      red = 4'b0000;
		   green = 4'b0000;
		   blue = 4'b0000;
		   $display("32");
		   end
	    end
       if (SW[4]==1)begin
	//1'b1:begin
	    if(col != 10'd0000 && col != 10'd0060 && row != 9'd480 && row != 9'd400)
	      begin
	      red = 4'b1111;
		   green = 4'b1111;
		   blue = 4'b1111;
		   $display("32");
		   end
	    end
       else if (SW[5]==1)begin
	//1'b1:begin
	      blue = 4'b1111;
	      $display("42");
	    end
       else if (SW[6]==1)begin
	//1'b1:begin
	     green = 4'b1111;
	     $display("52");
	    end
       else if (SW[7]==1)begin
	//1'b1:begin
	     red = 4'b1111;
	     $display("62");
	    end
		end
	end
  else if (SW[8]==1 && SW[9]==1)begin
	//2'b11:begin
	  if(col<=10'd0640 && col>=10'd0580 && row<=9'd480 && row >=9'd400)
	   begin
	    red = 4'b0000;
		 green = 4'b0000;
		 blue = 4'b0000;
		 $display("74");
		 if (SW[4]==0)begin
	//1'b1:begin
	    if(col == 10'd0640 || col == 10'd0580 || row == 9'd400 || row == 9'd480)
	      begin
	      red = 4'b0000;
		   green = 4'b0000;
		   blue = 4'b0000;
		   $display("32");
		   end
	    end
       if (SW[4]==1)begin
	//1'b1:begin
	    if(col != 10'd0580 && col != 10'd0640 && row != 9'd400 && row != 9'd480)
	      begin
	      red = 4'b1111;
		   green = 4'b1111;
		   blue = 4'b1111;
		   $display("32");
		   end
	    end
       else if (SW[5]==1)begin
	//1'b1:begin
	      blue = 4'b1111;
	      $display("42");
	    end
       else if (SW[6]==1)begin
	//1'b1:begin
	     green = 4'b1111;
	     $display("52");
	    end
       else if (SW[7]==1)begin
	//1'b1:begin
	     red = 4'b1111;
	     $display("62");
	    end
		end
	end
end

endmodule
