
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================
`define ss_0 7'b 1000000
`define ss_1 7'b 1111001
`define ss_2 7'b 0100100
`define ss_3 7'b 0110000
`define ss_4 7'b 0011001
`define ss_5 7'b 0010010
`define ss_6 7'b 0000010
`define ss_7 7'b 1111000
`define ss_8 7'b 0000000
`define ss_9 7'b 0010000
`define ss_a 7'b 0001000
`define ss_b 7'b 0000011
`define ss_c 7'b 1000110
`define ss_d 7'b 0100001
`define ss_e 7'b 0000110
`define ss_f 7'b 0001110

module FPGA_Board(

	//////////// SEG7 //////////
	output		     [7:0]		HEX0,
	output		     [7:0]		HEX1,
	output		     [7:0]		HEX2,
	output		     [7:0]		HEX3,
	output		     [7:0]		HEX4,
	output		     [7:0]		HEX5,

	//////////// KEY //////////
	input 		     [1:0]		KEY,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW
);



//=======================================================
//  REG/WIRE declarations
//=======================================================




//=======================================================

//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================



reg [5:0] a;
reg [5:0] b;
reg [5:0] c;

always @(*)begin
 case(SW) 
   3'b000:begin
	  a = 6'b000000;
	  b = 6'b000000;
     c = 6'b000000;
   end
   3'b001:begin 
	  a = 6'b000001;
	  b = 6'b000001;
     c = 6'b000001;
   end	  
   3'b010:begin 
	  a = 6'b000010;
	  b = 6'b000010;
     c = 6'b000010;
   end	  
   3'b011:begin 
	  a = 6'b111111;
	  b = 6'b111111;
     c = 6'b111111;
   end	  	
 endcase
end

wire cin;
wire co1,co2;
wire [7:0] summ;

add3 dadd3(.a(a), .b(b), .c(c), .ci(cin), .sumall(summ), .cooo1(co1), .cooo2(co2) );

reg [6:0] ssg1,ssg2;

always @(*) begin
   case(summ[3:0])
	 0: ssg1 = `ss_0 ;
	 1: ssg1 = `ss_1 ;
	 2: ssg1 = `ss_2 ;
	 3: ssg1 = `ss_3 ;
	 4: ssg1 = `ss_4 ;
	 5: ssg1 = `ss_5 ;
	 6: ssg1 = `ss_6 ;
	 7: ssg1 = `ss_7 ;
	 8: ssg1 = `ss_8 ;
	 9: ssg1 = `ss_9 ;
	 10: ssg1 = `ss_a ;
	 11: ssg1 = `ss_b ;
	 12: ssg1 = `ss_c ;
	 13: ssg1 = `ss_d ;
	 14: ssg1 = `ss_e ;
	 15: ssg1 = `ss_f ; 
 endcase
 
   case(summ[7:4])
	 0: ssg2 = `ss_0 ;
	 1: ssg2 = `ss_1 ;
	 2: ssg2 = `ss_2 ;
	 3: ssg2 = `ss_3 ;
	 4: ssg2 = `ss_4 ;
	 5: ssg2 = `ss_5 ;
	 6: ssg2 = `ss_6 ;
	 7: ssg2 = `ss_7 ;
	 8: ssg2 = `ss_8 ;
	 9: ssg2 = `ss_9 ;
	 10: ssg2 = `ss_a ;
	 11: ssg2 = `ss_b ;
	 12: ssg2 = `ss_c ;
	 13: ssg2 = `ss_d ;
	 14: ssg2 = `ss_e ;
	 15: ssg2 = `ss_f ; 
 endcase

end
assign HEX0 = ssg1;
assign HEX1 = ssg2;
assign HEX2 = 8'b11111111;
assign HEX3 = 8'b11111111;
assign HEX4 = 8'b11111111;
assign HEX5 = 8'b11111111;

endmodule
