
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================
`define ss_0 7'b 1000000
`define ss_1 7'b 1111001
`define ss_2 7'b 0100100
`define ss_3 7'b 0110000
`define ss_4 7'b 0001101
`define ss_5 7'b 0010010
`define ss_6 7'b 0000001
`define ss_7 7'b 1111000
`define ss_8 7'b 0000000
`define ss_9 7'b 0010000
`define ss_a 7'b 0001000
`define ss_b 7'b 0000011
`define ss_c 7'b 1000011
`define ss_d 7'b 0100001
`define ss_e 7'b 0000110
`define ss_f 7'b 0001110

module seg7(

	//////////// SEG7 //////////
	output		     [7:0]		HEX0,
	output		     [7:0]		HEX1,
	output		     [7:0]		HEX2,
	output		     [7:0]		HEX3,
	output		     [7:0]		HEX4,
	output		     [7:0]		HEX5,

	//////////// KEY //////////
	input 		     [1:0]		KEY,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW
);



//=======================================================
reg [6:0] segs;
//=======================================================




//=======================================================

always @(*) begin
   case(SW)
	 0: segs = `ss_0 ;
	 1: segs = `ss_1 ;
	 2: segs = `ss_2 ;
	 3: segs = `ss_3 ;
	 4: segs = `ss_4 ;
	 5: segs = `ss_5 ;
	 6: segs = `ss_6 ;
	 7: segs = `ss_7 ;
	 8: segs = `ss_8 ;
	 9: segs = `ss_9 ;
	 10: segs = `ss_a ;
	 11: segs = `ss_b ;
	 12: segs = `ss_c ;
	 13: segs = `ss_d ;
	 14: segs = `ss_e ;
	 15: segs = `ss_f ; 
 endcase
end
//=======================================================



endmodule
