
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================
`define ss_0 7'b 1000000
`define ss_1 7'b 1111001
`define ss_2 7'b 0100100
`define ss_3 7'b 0110000
`define ss_4 7'b 0011001
`define ss_5 7'b 0010010
`define ss_6 7'b 0000010
`define ss_7 7'b 1111000
`define ss_8 7'b 0000000
`define ss_9 7'b 0010000
`define ss_a 7'b 0001000
`define ss_b 7'b 0000011
`define ss_c 7'b 1000110
`define ss_d 7'b 0100001
`define ss_e 7'b 0000110
`define ss_f 7'b 0001110

module lab3_FPGA(

	//////////// SEG7 //////////
	output		     [7:0]		HEX0,
	output		     [7:0]		HEX1,
	output		     [7:0]		HEX2,
	output		     [7:0]		HEX3,
	output		     [7:0]		HEX4,
	output		     [7:0]		HEX5,

	//////////// KEY //////////
	input 		     [1:0]		KEY,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW
);



reg [3:0] test_in;
//reg [7:0] comp_in;
reg [127:0] test_data;
wire [127:0] test_data_t;
wire [3:0]num_match_low;
wire [3:0]num_match_2nd_low;
wire match;
wire [14:0] kkk;
always@(SW)begin
 test_in = SW; 
end
testrom tr(.addr(test_in), .data(test_data_t));
always@(*)begin
 test_data = test_data_t;
end

compare_top cmptp(.in0(test_data[7:0]), .in1(test_data[15:8]), .in2(test_data[23:16]),
               .in3(test_data[31:24]), .in4(test_data[39:32]), .in5(test_data[47:40]), 
               .in6(test_data[55:48]), .in7(test_data[63:56]), .in8(test_data[71:64]), 
               .in9(test_data[79:72]), .ina(test_data[87:80]), .inb(test_data[95:88]), 
               .inc(test_data[103:96]), .ind(test_data[111:104]), .ine(test_data[119:112]), 
               .inf(test_data[127:120]), .match(match), .num_match_low(num_match_low), .num_match_2nd_low(num_match_2nd_low));
reg [6:0] ssg1,ssg2;
always @(*) begin
   case(num_match_2nd_low)
	 0: ssg1 = `ss_0 ;
	 1: ssg1 = `ss_1 ;
	 2: ssg1 = `ss_2 ;
	 3: ssg1 = `ss_3 ;
	 4: ssg1 = `ss_4 ;
	 5: ssg1 = `ss_5 ;
	 6: ssg1 = `ss_6 ;
	 7: ssg1 = `ss_7 ;
	 8: ssg1 = `ss_8 ;
	 9: ssg1 = `ss_9 ;
	 10: ssg1 = `ss_a ;
	 11: ssg1 = `ss_b ;
	 12: ssg1 = `ss_c ;
	 13: ssg1 = `ss_d ;
	 14: ssg1 = `ss_e ;
	 15: ssg1 = `ss_f ; 
 endcase
 
   case(num_match_low)
	 0: ssg2 = `ss_0 ;
	 1: ssg2 = `ss_1 ;
	 2: ssg2 = `ss_2 ;
	 3: ssg2 = `ss_3 ;
	 4: ssg2 = `ss_4 ;
	 5: ssg2 = `ss_5 ;
	 6: ssg2 = `ss_6 ;
	 7: ssg2 = `ss_7 ;
	 8: ssg2 = `ss_8 ;
	 9: ssg2 = `ss_9 ;
	 10: ssg2 = `ss_a ;
	 11: ssg2 = `ss_b ;
	 12: ssg2 = `ss_c ;
	 13: ssg2 = `ss_d ;
	 14: ssg2 = `ss_e ;
	 15: ssg2 = `ss_f ; 
 endcase

end
assign HEX0 = ssg1;
assign HEX1 = ssg2;
assign HEX2 = 8'b11111111;
assign HEX3 = 8'b11111111;
assign HEX4 = 8'b11111111;
assign HEX5 = 8'b11111111;

endmodule
